-- CodeArena core schema.
--
-- Conventions:
--   * surrogate bigint identity keys everywhere
--   * enums are stored as varchar + CHECK rather than native PG enums, so adding a value
--     is an ordinary migration instead of an ALTER TYPE that cannot run in a transaction
--   * timestamps are timestamptz; the application writes them via JPA auditing, the DB
--     defaults exist so SQL-seeded rows are still well formed

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    rating        INTEGER      NOT NULL DEFAULT 1200,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_users_rating CHECK (rating BETWEEN 0 AND 4000)
);

CREATE TABLE tags
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    CONSTRAINT uk_tags_name UNIQUE (name)
);

-- Directed edges of the tag prerequisite DAG: "you should be comfortable with
-- prerequisite_tag_id before tag_id is recommended to you". Consumed by the topological
-- sort in the recommendation engine (Phase 5).
CREATE TABLE tag_prerequisites
(
    tag_id              BIGINT NOT NULL,
    prerequisite_tag_id BIGINT NOT NULL,
    PRIMARY KEY (tag_id, prerequisite_tag_id),
    CONSTRAINT fk_tag_prereq_tag FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE,
    CONSTRAINT fk_tag_prereq_prereq FOREIGN KEY (prerequisite_tag_id) REFERENCES tags (id) ON DELETE CASCADE,
    CONSTRAINT ck_tag_prereq_no_self_loop CHECK (tag_id <> prerequisite_tag_id)
);

CREATE TABLE problems
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(200) NOT NULL,
    slug            VARCHAR(200) NOT NULL,
    difficulty      VARCHAR(10)  NOT NULL,
    rating          INTEGER      NOT NULL,
    time_limit_ms   INTEGER      NOT NULL DEFAULT 1000,
    memory_limit_mb INTEGER      NOT NULL DEFAULT 256,
    created_by      BIGINT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_problems_slug UNIQUE (slug),
    CONSTRAINT fk_problems_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT ck_problems_difficulty CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    CONSTRAINT ck_problems_rating CHECK (rating BETWEEN 0 AND 4000),
    CONSTRAINT ck_problems_time_limit CHECK (time_limit_ms BETWEEN 100 AND 20000),
    CONSTRAINT ck_problems_memory_limit CHECK (memory_limit_mb BETWEEN 16 AND 1024)
);

CREATE INDEX idx_problems_rating ON problems (rating);
CREATE INDEX idx_problems_difficulty ON problems (difficulty);
CREATE INDEX idx_problems_created_at ON problems (created_at DESC);

CREATE TABLE problem_tags
(
    problem_id BIGINT NOT NULL,
    tag_id     BIGINT NOT NULL,
    PRIMARY KEY (problem_id, tag_id),
    CONSTRAINT fk_problem_tags_problem FOREIGN KEY (problem_id) REFERENCES problems (id) ON DELETE CASCADE,
    CONSTRAINT fk_problem_tags_tag FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE
);

CREATE INDEX idx_problem_tags_tag ON problem_tags (tag_id);

CREATE TABLE submissions
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL,
    problem_id   BIGINT      NOT NULL,
    language     VARCHAR(20) NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
    verdict      VARCHAR(10),
    runtime_ms   INTEGER,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_submissions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_submissions_problem FOREIGN KEY (problem_id) REFERENCES problems (id) ON DELETE CASCADE,
    CONSTRAINT ck_submissions_language CHECK (language IN ('JAVA', 'PYTHON', 'CPP', 'GO', 'JAVASCRIPT')),
    CONSTRAINT ck_submissions_status CHECK (status IN ('QUEUED', 'RUNNING', 'DONE')),
    CONSTRAINT ck_submissions_verdict CHECK (verdict IS NULL OR verdict IN ('AC', 'WA', 'TLE', 'RTE', 'CE')),
    -- a verdict only exists once judging finished, and vice versa
    CONSTRAINT ck_submissions_verdict_matches_status CHECK (
        (status = 'DONE' AND verdict IS NOT NULL) OR (status <> 'DONE' AND verdict IS NULL)
        ),
    CONSTRAINT ck_submissions_runtime CHECK (runtime_ms IS NULL OR runtime_ms >= 0)
);

CREATE INDEX idx_submissions_user_submitted ON submissions (user_id, submitted_at DESC);
CREATE INDEX idx_submissions_problem ON submissions (problem_id);
-- Supports "which problems has this user already solved?", the hottest read in the
-- recommendation engine's candidate-pool filter.
CREATE INDEX idx_submissions_user_problem_verdict ON submissions (user_id, problem_id, verdict);

-- Denormalised per-user, per-tag counters. Maintained when a verdict is written back, and
-- read as a whole row set to build the tag-proficiency vector.
CREATE TABLE user_tag_stats
(
    user_id       BIGINT  NOT NULL,
    tag_id        BIGINT  NOT NULL,
    solved_count  INTEGER NOT NULL DEFAULT 0,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, tag_id),
    CONSTRAINT fk_user_tag_stats_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_tag_stats_tag FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE,
    CONSTRAINT ck_user_tag_stats_counts CHECK (solved_count >= 0 AND attempt_count >= solved_count)
);
