-- Authentication support: federated accounts and revocable refresh tokens.

-- ---------------------------------------------------------------------------------------
-- Federated identity
--
-- A Google-authenticated account has no password of ours to store. Rather than inventing a
-- sentinel value, password_hash becomes nullable and a CHECK ties its presence to the
-- provider: a LOCAL account must have one, a federated account must not. That makes
-- "federated user with a password nobody set" unrepresentable rather than merely unlikely.
-- ---------------------------------------------------------------------------------------
ALTER TABLE users
    ALTER COLUMN password_hash DROP NOT NULL;

ALTER TABLE users
    ADD COLUMN auth_provider VARCHAR(20) NOT NULL DEFAULT 'LOCAL',
    ADD COLUMN provider_id   VARCHAR(255);

ALTER TABLE users
    ADD CONSTRAINT ck_users_auth_provider CHECK (auth_provider IN ('LOCAL', 'GOOGLE')),
    ADD CONSTRAINT ck_users_password_matches_provider CHECK (
        (auth_provider = 'LOCAL' AND password_hash IS NOT NULL)
            OR (auth_provider <> 'LOCAL' AND password_hash IS NULL)
        ),
    ADD CONSTRAINT ck_users_provider_id_matches_provider CHECK (
        (auth_provider = 'LOCAL' AND provider_id IS NULL)
            OR (auth_provider <> 'LOCAL' AND provider_id IS NOT NULL)
        );

-- Partial unique index: one account per (provider, subject). LOCAL rows all have a NULL
-- provider_id and are excluded, so they do not collide with each other.
CREATE UNIQUE INDEX uk_users_provider_identity
    ON users (auth_provider, provider_id)
    WHERE provider_id IS NOT NULL;

-- ---------------------------------------------------------------------------------------
-- Refresh tokens
--
-- Stored as a SHA-256 hex digest, never in the clear: a leaked database dump should not hand
-- an attacker usable sessions. SHA-256 rather than BCrypt is deliberate here - the token is
-- 256 bits of CSPRNG output, so there is no low-entropy secret to slow a brute-forcer down,
-- and login latency matters on a lookup that happens on every refresh.
--
-- replaced_by_id records rotation, which is what makes reuse detection possible: presenting an
-- already-rotated token means it leaked, and the whole chain gets revoked.
-- ---------------------------------------------------------------------------------------
CREATE TABLE refresh_tokens
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT      NOT NULL,
    -- VARCHAR rather than CHAR: Postgres reports CHAR(n) as bpchar, which Hibernate's
    -- schema validation rejects against a String field. The length is fixed by SHA-256 anyway,
    -- so CHAR bought nothing but a startup failure.
    token_hash     VARCHAR(64) NOT NULL,
    issued_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at     TIMESTAMPTZ NOT NULL,
    revoked_at     TIMESTAMPTZ,
    replaced_by_id BIGINT,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_refresh_tokens_replaced_by FOREIGN KEY (replaced_by_id) REFERENCES refresh_tokens (id) ON DELETE SET NULL,
    CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT ck_refresh_tokens_expiry CHECK (expires_at > issued_at)
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);
-- Supports the periodic purge of tokens that are past use.
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);
