package com.codearena.api.mongo;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.core.io.ClassPathResource;
import org.springframework.dao.DataAccessException;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.io.InputStream;
import java.util.List;

/**
 * Loads the bundled test cases into MongoDB.
 *
 * <p>Upserts on every start, for the same reasons as {@link ProblemStatementSeeder}: MongoDB has
 * no schema to version, so the useful property is "ends in a known state" rather than "ran once".
 * Regenerating {@code problem-test-cases.json} and restarting is the whole update procedure.
 *
 * <p>The file is generated by {@code tools/generate_test_cases.py} from reference solutions
 * rather than written by hand. A wrong expected output is the worst defect a judge can have -
 * it fails correct submissions, and there is nothing in the judge's own code to find - so the
 * answers come from running a known-good implementation rather than from somebody's typing.
 */
@Component
public class ProblemTestCaseSeeder {

    private static final Logger log = LoggerFactory.getLogger(ProblemTestCaseSeeder.class);

    /** Used only in the "already populated" log line. */
    private static final String WHAT = "problem test case";

    private static final String RESOURCE = "mongo/problem-test-cases.json";

    private final ProblemTestCaseRepository repository;
    private final ObjectMapper objectMapper;

    public ProblemTestCaseSeeder(ProblemTestCaseRepository repository, ObjectMapper objectMapper) {
        this.repository = repository;
        this.objectMapper = objectMapper;
    }

    @EventListener(ApplicationReadyEvent.class)
    public void seed() {
        // First run only. These documents are editable from the admin UI, and re-seeding on every
        // startup would silently revert an editor's work on the next deploy - a data-loss bug that
        // looks like the save button not working. The bundled JSON is the starting catalogue, not
        // the source of truth for a database that has since been used.
        //
        // The check is "is the collection empty" rather than a per-document merge because a
        // half-seeded collection is not a state this can reason about: a problem deleted on
        // purpose would reappear, which is the same bug wearing a different hat.
        long existing = repository.count();
        if (existing > 0) {
            log.info("MongoDB already holds {} {} documents; leaving them alone",
                    existing, WHAT);
            return;
        }

        List<TestCaseDocument> documents;
        try (InputStream in = new ClassPathResource(RESOURCE).getInputStream()) {
            documents = List.of(objectMapper.readValue(in, TestCaseDocument[].class));
        } catch (IOException e) {
            // A malformed bundled resource is a build problem, not a runtime condition.
            log.error("Could not read {}: {}", RESOURCE, e.getMessage());
            return;
        }

        try {
            repository.saveAll(documents.stream().map(TestCaseDocument::toDocument).toList());
            int cases = documents.stream().mapToInt(d -> d.cases().size()).sum();
            log.info("Seeded {} test cases across {} problems into MongoDB",
                    cases, documents.size());
        } catch (DataAccessException e) {
            // Judging degrades to "this problem has no cases", which the judge reports honestly
            // rather than guessing - so this is a warning, not a reason to refuse to serve.
            log.warn("Could not seed test cases: {}. Problems will have none until this succeeds.",
                    e.getMessage());
        }
    }

    /** The JSON shape, kept separate so the file stays camelCase and readable. */
    record TestCaseDocument(String slug, List<Case> cases) {

        ProblemTestCases toDocument() {
            return new ProblemTestCases(slug, cases.stream()
                    .map(c -> new ProblemTestCases.Case(
                            c.index(), c.input(), c.expectedOutput(), c.sample()))
                    .toList());
        }

        record Case(int index, String input, String expectedOutput, boolean sample) {
        }
    }
}
